### ISSUE TITLE
Nothing rendering

### ISSUE THREAD

**Issue by jreniel** [aleb2000/split-yew#2]
Hello again!
I just picked up where I left off on the web component of my project, and so far split-yew compiles with the latest.
However, nothing shows up!
My html looks like this:
```html
<!doctype html>                                                             
<html>                                                                      
  <head>                                                                    
    <meta charset="utf-8" />                                                
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <title>Yew App</title> -->                                         
    <script type="importmap">                                               
      {                                                                     
        "imports": {                                                        
          "split.js": "https://unpkg.com/split.js@1.6.5/dist/split.es.js"   
        }                                                                   
      }                                                                     
    </script>                                                               
  </head>                                                                   
  <body></body>                                                             
</html>                                                                     
```
My test component looks like this:
```Rust
use split_yew::Split;                     
use yew::prelude::*;                      
                                          
#[function_component(CompA)]              
pub fn comp_a() -> Html {                 
    html! {                               
        <>                                
        {"hello"}                         
        </>                               
    }                                     
}                                         
                                          
#[function_component(CompB)]              
pub fn comp_b() -> Html {                 
    html! {                               
        <>                                
        {"hello2"}                        
        </>                               
    }                                     
}                                         
#[function_component(App)]                
pub fn app() -> Html {                    
    html! {                               
        <>                                
            <Split                        
            min_size={500.0}              
            min_sizes={vec![100.0, 200.0]}
            >                             
            <CompA />                     
            <CompB />                     
            </Split>                      
            {"test2"}                     
        </>                               
    }                                     
}                                         
```

But there's no gutter, or any signs of Split. The text does render, but as if there was no split at all!
Help?
Thanks!

**Comment by aleb2000** [comment]
The problem you are encountering is due to an error thrown inside split.js itself. I'm pretty sure split.js only works on HTML elements and not on text nodes alone. To fix the error you can just make sure the text of each component is within a div (or some other HTML element).

```rust
#[function_component(CompA)]              
pub fn comp_a() -> Html {                 
    html! {                               
        <div>                                
        {"hello"}                         
        </div>                               
    }                                     
}
#[function_component(CompB)]              
pub fn comp_b() -> Html {                 
    html! {                               
        <div>                                
        {"hello2"}                        
        </div>                             
    }                                     
}  
```

Then the gutter is created.

**Comment by aleb2000** [comment]
Mind you, the Split component does not set any CSS style at all, hence you will not see the gutter nor will you be able to drag it by default. You will need to set the style of the split container to flex, and add some style to the gutter to make it visible. You can look at the CSS used by the split.js demo at https://split.js.org/ for some inspiration.

**Comment by aleb2000** [comment]
Also take a look at [the official split.js documentation on CSS](https://github.com/nathancahill/split/tree/master/packages/splitjs#css)

**Comment by jreniel** [comment]
Ok, that makes sense! I'm not really a web developer, but I'm trying to make an interactive interface for the stuff that I'm building. It'll take a a while to figure out how to put the CSS in while keeping it "clean". For example, I'm inclined to use stylist. Would you recommend that as a sound approach?
Thanks again for your super fast responses!

**Comment by aleb2000** [comment]
I'm not much of a web developer either, so I feel your pain! Regarding Stylist I can't really say as I have never used it, however it doesn't look like a bad approach. I developed this library for a little project I was doing and there I used TailwindCSS (recommended by a friend of mine), which, after some setup worked surprisingly well even in Rust.

**Comment by jreniel** [comment]
Thanks, that makes sense! To share what I am trying to do, take a look at:
https://www.myroms.org/wiki/Vertical_S-coordinate
Let's say I already implemented all the math parts to generate those grids, but if you look at the bottom of that page you will see some static images. I'd like to make a dynamic interface where I can change the parameters and see how the grid changes in real time. Right now I have to generate and plot separately, iteratively. If I could see how the grid changes as I change the parameters, it would be tremendously helpful.

**Comment by aleb2000** [comment]
Not gonna lie, that looks quite complicated, so good luck on that! It does sound like an very useful tool though. 
One thing I am curious about is, why choose Rust for the web interface in this particular application? Is it because you already implemented the math in Rust?
Anyway, I will close this issue since the original problem is resolved!

**Comment by jreniel** [comment]
Yes, Rust is too awesome to ignore, and I built the grid generators in Rust, so I'm sure I can reuse them through yew. I feel Rust can take a strong place in numerical modeling. Particularly because we could make things a lot more cohesive and more modern that the Fortran approach, where cohesion is not necessarily a thing.

**Comment by jreniel** [comment]
Thanks a lot for your help, btw!

**Comment by aleb2000** [comment]
Btw, your issue made me think that maybe I should specify in the README that users should include their own CSS, possibly with a basic example. I guess I will do that when I have the time.

**Comment by jreniel** [comment]
I still haven't been able to make it work but will post my solution when it does, thanks!

**Comment by aleb2000** [comment]
If you have more questions, feel free to ask. I won't necessarily always answer as quickly as right now, but I will get back eventually!

**Comment by jreniel** [comment]
Hi @aleb2000 , I think you are right that tailwind css is probably a better option for people like me that know very little about CSS. I don't mean to take up your time, but if possible, and since you have done this before, could you illustrate how to get the split view to render with tailwind? For this illustration I don't need to know how the tailwind installation goes on a yew project, I already have that part figured out. Just how to use it in order to get the split to render. If you can help with that I'll appreciate it immensely. Thanks!

**Comment by aleb2000** [comment]
Hi @jreniel, I think setting it as `class="flex flex-row"` should already be enough (or flex-col depending on split direction).
For an example that uses tailwind you can take a look at [yew-playground's use of split-yew](https://github.com/yewstack/yew-playground/blob/47a481cd869efb1d521bb33a11b20f319ee3d751/frontend/src/app.rs#L93). You can see the split in the [webpage of the playground](https://play.yew.rs/) (the gutter is collapsed at the beginning but you can always drag it).
To make the gutter visible [take a look at the CSS](https://github.com/yewstack/yew-playground/blob/47a481cd869efb1d521bb33a11b20f319ee3d751/frontend/styles/globals.scss#L12) (sadly we can't use tailwind for this).
Make sure to include the css stylesheet in your index.html as well.

**Comment by jreniel** [comment]
Thanks @aleb2000 ! 
I've been looking like crazy for a live example that uses split-yew and couldn't find any.
I think it would be beneficial if you added the yew-playground link on the readme.
Thanks again!

**Comment by aleb2000** [comment]
I was planning on writing an actual demo to include in the repo, however I never got around doing it. In the meantime I will add the link for sure.

**Comment by jreniel** [comment]
After adding display: flex using sylist, now I'm finally making progress!!

**Comment by jreniel** [comment]
Any chance you'll ever do split-grid?

**Comment by aleb2000** [comment]
I'm not sure, the reason why I made this library in the first place was because I needed a resizable split for a little project I was working on, and the current split-yew does the job just fine, then I decided to publish it because there was nothing else publicly available. I currently don't have any need for split-grid. Heck, I have never even used grid layouts before (look how good of a web dev I am :) ).

I thought about working on it (maybe as an additional "grid" feature to the crate), but as it stands I don't have any reason to do it any time soon. If you (or other people) need it I might consider it, although I cannot give guarantees on the timeline.

On the other hand I'm open to accept pull requests if anyone is interested in working on it :wink:.

**Comment by jreniel** [comment]
No prob, it's not like I actually need it, it was more like a curiosity question. Great work though, thanks for sharing it!

**Comment by jreniel** [comment]
Ok, I finally made it work. Here's a minimal working example:
```Rust
#[function_component(App)]                                              
pub fn app() -> Html {                                                  
    let split_style = use_style!("display: flex; flex-direction: row;");
    let gutter_style = ".gutter {                                       
            background-color: #eee;                                     
            background-repeat: no-repeat;                               
            background-position: 50%;                                   
        }";                                                             
                                                                        
    html! {                                                             
        <>                                                              
            <style>{gutter_style}</style>                               
            <Split                                                      
            class={split_style}                                         
            >                                                           
            <CompA />                                                   
            <CompB />                                                   
            </Split>                                                    
        </>                                                             
    }                                                                   
}                                                                       
```

The point that I had most trouble with was realizing I needed to inject a css selector specifically called .gutter, and add it as an inline style.
I haven't figured out how to do this using stylist, but at least now I can see the gutter, and I hope this helps others struggling to understand how to css in yew.
